import type { PromptVersion } from "@/lib/types";

export const mockPromptVersions: PromptVersion[] = [
  {
    id: "pv-014",
    version: 14,
    modelSlug: "anthropic/claude-sonnet-4.6",
    systemPrompt:
      "You are Edstellar's course discovery agent. Propose enterprise-grade instructor-led courses ...",
    status: "active",
    approvalRate: 0.64,
    runsObserved: 12,
    createdAt: "2026-05-10T00:00:00.000Z",
    notes: "Added the negotiation-skills constraint after three rejections last week.",
  },
  {
    id: "pv-013",
    version: 13,
    modelSlug: "anthropic/claude-sonnet-4.6",
    systemPrompt: "Earlier system prompt ...",
    status: "retired",
    approvalRate: 0.52,
    runsObserved: 8,
    createdAt: "2026-04-22T00:00:00.000Z",
    notes: "Replaced by v14 after CSRD content was missing.",
  },
  {
    id: "pv-015",
    version: 15,
    modelSlug: "openai/gpt-5",
    systemPrompt: "Experimental — GPT-5 variant of v14 ...",
    status: "candidate",
    approvalRate: null,
    runsObserved: 0,
    createdAt: "2026-05-15T00:00:00.000Z",
    notes: "Generated by the weekly self-regeneration job. Not yet promoted.",
  },
];
